export const READ_BOOK = 'BOOKS/READ';
export const UPLOAD_BOOKS = 'BOOKS/UPLOAD';
export const RECENTLY_OPENED = 'BOOKS/RECENTLY_OPENED';

export const LIST_BOOKS = 'BOOKS/LIST/ALL';
export const LIST_CREATOR = 'BOOKS/LIST/CREATOR';

export const READER_SETTINGS = 'SETTINGS/READER';
export const GENERAL_SETTINGS = 'SETTINGS/GENERAL';
export const BOOK_LIST_SETTINGS = 'SETTINGS/BOOK_LIST';
