export const READ_BOOK = 'BOOKS/READ';
export const UPLOAD_BOOKS = 'BOOKS/UPLOAD';
export const RECENTLY_OPENED = 'BOOKS/RECENTLY_OPENED';

export const LIST_TAGS = 'BOOKS/LIST/TAGS';
export const LIST_BOOKS = 'BOOKS/LIST/ALL';
export const LIST_SERIES = 'BOOKS/LIST/SERIES';
export const LIST_RATINGS = 'BOOKS/LIST/RATINGS';
export const LIST_AUTHORS = 'BOOKS/LIST/AUTHORS';
export const LIST_AUTHOR_SORT = 'BOOKS/LIST/AUTHOR_SORT';

export const READER_SETTINGS = 'SETTINGS/READER';
export const GENERAL_SETTINGS = 'SETTINGS/GENERAL';
export const BOOK_LIST_SETTINGS = 'SETTINGS/BOOK_LIST';
